services:
  ispyagentdvr:
    image: mekayelanik/ispyagentdvr:gpu-hwaccel-latest
    container_name: ispyagentdvr
    environment:
      - PUID=1000
      - PGID=1000
      - WEBUI_PORT=8090 
      - TZ=Ameriaca/Sao_Paulo
    volumes:
      - /Users/vagner/Desenvolvimento/python/camera/config:/AgentDVR/Media/XML
      - /Users/vagner/Desenvolvimento/python/camera/recordings:/AgentDVR/Media/WebServerRoot/Media
      - /Users/vagner/Desenvolvimento/python/camera/commands:/AgentDVR/Commands
    ports:
      - 8090:8090
      - 3478:3478/udp
      - 40000-40010:50000-50010/udp
    restart: unless-stopped